const API='http://localhost:8000';
let token=localStorage.getItem('access_token');
let currentUser=null;
const $=id=>document.getElementById(id);
async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(token)headers.Authorization=`Bearer ${token}`;const r=await fetch(API+path,{...options,headers});if(r.status===401){logout(false)};return r}
function showApp(){ $('loginPage').classList.add('hidden');$('app').classList.remove('hidden');$('userName').textContent=currentUser.full_name||currentUser.username;$('userRole').textContent=currentUser.role;$('avatar').textContent=(currentUser.full_name||currentUser.username)[0].toUpperCase();render('dashboard')}
function logout(callApi=true){if(callApi&&token)fetch(API+'/auth/logout',{method:'POST',headers:{Authorization:`Bearer ${token}`}}).catch(()=>{});token=null;localStorage.removeItem('access_token');currentUser=null;$('app').classList.add('hidden');$('loginPage').classList.remove('hidden')}
async function login(e){e.preventDefault();$('loginError').textContent='Entrando...';try{const r=await fetch(API+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('username').value,password:$('password').value})});const d=await r.json();if(!r.ok){$('loginError').textContent=d.detail||'Usuário ou senha inválidos';return}token=d.access_token;localStorage.setItem('access_token',token);const me=await api('/auth/me');currentUser=await me.json();showApp()}catch(err){$('loginError').textContent='Não foi possível conectar à API.'}}
async function render(page){const labels={dashboard:['Dashboard','Visão geral do Sistema JMC'],users:['Usuários','Controle de acesso e usuários'],clientes:['Clientes','Cadastro e relacionamento com clientes'],produtos:['Produtos / Estoque','Controle de produtos e estoque'],vendas:['Vendas','Acompanhamento de vendas'],entregas:['Entregas','Controle de cargas e entregas'],financeiro:['Financeiro','Visão financeira da empresa']};$('pageName').textContent=labels[page][0];$('title').textContent=labels[page][0];$('subtitle').textContent=labels[page][1];document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));if(page==='dashboard'){$('pageContent').innerHTML=`<div class="cards"><div class="card"><h3>Vendas hoje</h3><div class="value">R$ 0,00</div></div><div class="card"><h3>Entregas</h3><div class="value">0</div></div><div class="card"><h3>Clientes</h3><div class="value">0</div></div><div class="card"><h3>Estoque</h3><div class="value">0 itens</div></div></div><div class="panel"><h2>Bem-vindo ao Sistema JMC</h2><p class="muted">A autenticação está ativa. Os módulos comerciais, estoque, vendas, entregas e financeiro serão conectados à API nas próximas etapas.</p></div>`}else if(page==='users')await renderUsers();else $('pageContent').innerHTML=`<div class="panel"><h2>${labels[page][0]}</h2><p class="muted">Módulo preparado para implementação.</p></div>`}
async function renderUsers(){if(currentUser.role!=='admin'){$('pageContent').innerHTML='<div class="panel"><h2>Acesso restrito</h2><p class="muted">Somente administradores podem gerenciar usuários.</p></div>';return}const r=await api('/auth/users');const users=await r.json();$('pageContent').innerHTML=`<div class="panel"><div style="display:flex;justify-content:space-between;align-items:center"><h2>Usuários cadastrados</h2><button class="btn" onclick="createUser()">+ Novo usuário</button></div><table class="table"><thead><tr><th>ID</th><th>Usuário</th><th>Nome</th><th>Perfil</th><th>Status</th></tr></thead><tbody>${users.map(u=>`<tr><td>${u.id}</td><td>${u.username}</td><td>${u.full_name||'-'}</td><td>${u.role}</td><td><span class="badge">${u.is_active?'Ativo':'Inativo'}</span></td></tr>`).join('')}</tbody></table></div>`}
async function createUser(){const username=prompt('Usuário:');if(!username)return;const full_name=prompt('Nome completo:');if(!full_name)return;const password=prompt('Senha (mínimo 8 caracteres):');if(!password)return;const role=prompt('Perfil: admin, manager ou employee','employee');if(!role)return;const r=await api('/auth/users',{method:'POST',body:JSON.stringify({username,full_name,password,role})});if(!r.ok){const d=await r.json();alert(d.detail||'Erro ao criar usuário');return}renderUsers()}
$('login').addEventListener('submit',login);$('logout').addEventListener('click',()=>logout(true));document.querySelectorAll('.nav button').forEach(b=>b.addEventListener('click',()=>render(b.dataset.page)));
(async()=>{if(token){const r=await api('/auth/me');if(r.ok){currentUser=await r.json();showApp()}else logout(false)}})();
